<?php

$curl = curl_init();
$channel =$_GET['c'];

$url="https://spapi.zee5.com/singlePlayback/getDetails?channel_id=$channel&device_id=o6MhX3zFu1lGHBKrR2uW000000000000&platform_name=desktop_web&translation=en&user_language=en,hi,mr&country=IN&state=BR&app_version=2.50.50&user_type=guest&check_parental_control=false&ppid=o6MhX3zFu1lGHBKrR2uW000000000000&version=12";

curl_setopt_array($curl, array(
  CURLOPT_URL => $url,
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS =>'{
  "x-access-token": " eyJ0eXAiOiJqd3QiLCJhbGciOiJIUzI1NiJ9.eyJwcm9kdWN0X2NvZGUiOiJ6ZWU1QDk3NSIsInBsYXRmb3JtX2NvZGUiOiJXZWJAJCF0Mzg3MTIiLCJpc3N1ZWRBdCI6IjIwMjItMDEtMDlUMTI6MzA6MDErMDAwMCIsInR0bCI6ODY0MDB9.ePH0EDWFySant4VASEzjLGP8NSo8SVu5oMMdWlsHIlw ",  
  "Authorization": " eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2NDE3MzcwMjYsImV4cCI6MTY3MzI3MzAyNiwiaXNzIjoiaHR0cHM6Ly91c2VyYXBpLnplZTUuY29tIiwiYXVkIjpbImh0dHBzOi8vdXNlcmFwaS56ZWU1LmNvbS9yZXNvdXJjZXMiLCJzdWJzY3JpcHRpb25hcGkiLCJ1c2VyYXBpIl0sImNsaWVudF9pZCI6InJlZnJlc2hfdG9rZW5fY2xpZW50Iiwic3ViIjoiNTU5NTViN2YtMmQ5Zi00Y2UyLTgxN2UtMTRmM2E4NzA5MzQyIiwiYXV0aF90aW1lIjoxNjQxNzM3MDI2LCJpZHAiOiJsb2NhbCIsInVzZXJfaWQiOiI1NTk1NWI3Zi0yZDlmLTRjZTItODE3ZS0xNGYzYTg3MDkzNDIiLCJzeXN0ZW0iOiJaNSIsImFjdGl2YXRpb25fZGF0ZSI6IjIwMjEtMDMtMTlUMTA6MTc6MDciLCJjcmVhdGVkX2RhdGUiOiIyMDIxLTAzLTE5VDEwOjE3OjA3IiwicmVnaXN0cmF0aW9uX2NvdW50cnkiOiJJTiIsInVzZXJfZW1haWwiOiJtb25hbGltb25hbGlwYXRpbEBnbWFpbC5jb20iLCJzdWJzY3JpcHRpb25zIjoiW3tcImlkXCI6XCI2N2Q5MzA5NC0yN2M3LTQ1ZDMtYWFmYS02NGI3MWNmNTQxODJcIixcInVzZXJfaWRcIjpcIjU1OTU1YjdmLTJkOWYtNGNlMi04MTdlLTE0ZjNhODcwOTM0MlwiLFwiaWRlbnRpZmllclwiOlwiQ1JNXCIsXCJzdWJzY3JpcHRpb25fcGxhblwiOntcImlkXCI6XCIwLTExLTE4NDJcIixcImFzc2V0X3R5cGVcIjoxMSxcInN1YnNjcmlwdGlvbl9wbGFuX3R5cGVcIjpcIlNWT0RcIixcInRpdGxlXCI6XCJQcmVtaXVtXCIsXCJvcmlnaW5hbF90aXRsZVwiOlwiUHJlbWl1bVwiLFwic3lzdGVtXCI6XCJaNVwiLFwiZGVzY3JpcHRpb25cIjpcIjUwJSBvZmYgb24g4oK5OTk5XCIsXCJiaWxsaW5nX2N5Y2xlX3R5cGVcIjpcImRheXNcIixcImJpbGxpbmdfZnJlcXVlbmN5XCI6MzY1LFwicHJpY2VcIjo0OTkuMCxcImN1cnJlbmN5XCI6XCJJTlJcIixcImNvdW50cnlcIjpcIklOXCIsXCJjb3VudHJpZXNcIjpbXCJJTlwiXSxcInN0YXJ0XCI6XCIyMDIxLTAyLTEyVDAwOjAwOjAwWlwiLFwiZW5kXCI6XCIyMDIyLTAzLTMxVDIzOjU5OjU5WlwiLFwib25seV9hdmFpbGFibGVfd2l0aF9wcm9tb3Rpb25cIjp0cnVlLFwicmVjdXJyaW5nXCI6ZmFsc2UsXCJwYXltZW50X3Byb3ZpZGVyc1wiOlt7XCJuYW1lXCI6XCJBbWF6b25JQVBcIixcInByb2R1Y3RfcmVmZXJlbmNlXCI6XCJ6ZWU1X29mZmVyX3BhY2tfaW5fMXlcIn0se1wibmFtZVwiOlwiUXdpa2NpbHZlclwifSx7XCJuYW1lXCI6XCJQYXlUTVwifSx7XCJuYW1lXCI6XCJKdXNQYXlcIn0se1wibmFtZVwiOlwiUGF5VVwifSx7XCJuYW1lXCI6XCJQYXl0bVFSXCJ9LHtcIm5hbWVcIjpcIlBheXRtUVJVUElcIn1dLFwicHJvbW90aW9uc1wiOltdLFwiYXNzZXRfdHlwZXNcIjpbNiwwLDldLFwiYXNzZXRfaWRzXCI6W10sXCJidXNpbmVzc190eXBlXCI6XCJmcmVlXCIsXCJiaWxsaW5nX3R5cGVcIjpcInByZW1pdW1cIixcIm51bWJlcl9vZl9zdXBwb3J0ZWRfZGV2aWNlc1wiOjMsXCJtb3ZpZV9hdWRpb19sYW5ndWFnZXNcIjpbXSxcInR2X3Nob3dfYXVkaW9fbGFuZ3VhZ2VzXCI6W10sXCJjaGFubmVsX2F1ZGlvX2xhbmd1YWdlc1wiOltdLFwiZHVyYXRpb25fdGV4dFwiOlwiOTk5XCIsXCJ2YWxpZF9mb3JfYWxsX2NvdW50cmllc1wiOnRydWUsXCJhbGxvd2VkX3BsYXliYWNrX2R1cmF0aW9uXCI6NixcIm9mZmVyX2lkXCI6NTgsXCJjYXRlZ29yeVwiOlwiZXZlbnRcIn0sXCJzdWJzY3JpcHRpb25fc3RhcnRcIjpcIjIwMjEtMDMtMTlUMTA6MjE6MzEuMjlaXCIsXCJzdWJzY3JpcHRpb25fZW5kXCI6XCIyMDIyLTAzLTE5VDIzOjU5OjU5WlwiLFwic3RhdGVcIjpcImFjdGl2YXRlZFwiLFwicmVjdXJyaW5nX2VuYWJsZWRcIjpmYWxzZSxcInBheW1lbnRfcHJvdmlkZXJcIjpcImNybVwiLFwiZnJlZV90cmlhbFwiOm51bGwsXCJjcmVhdGVfZGF0ZVwiOlwiMjAyMS0wMy0xOVQxMDoyMTozMS4yOVpcIixcImlwX2FkZHJlc3NcIjpcIjE1Ny4zMy4yMTcuMjJcIixcInJlZ2lvblwiOlwiTWFoYXJhc2h0cmFcIixcImFkZGl0aW9uYWxcIjp7XCJhbW91bnRcIjpcIjQ5OS4wMFwiLFwicGF5bWVudF90eG5faWRcIjpcIjEyNTQzODMzODgxXCIsXCJwYXltZW50bW9kZVwiOlwiUGF5VVwiLFwidHJhbnNhY3Rpb25faWRcIjpcIjQ0MDY3ODcxXzI2Qml1R3hOVGZTSDdPY1lcIixcImRpc2NvdW50X2Ftb3VudFwiOlwiMC4wMDAwXCIsXCJmcmVlX3RyaWFsXCI6bnVsbCxcIm9yaWdpbmFsX3VzZXJfYWdlbnRcIjpcIm9raHR0cC80LjguMVwiLFwicmVjdXJyaW5nX2VuYWJsZWRcIjpmYWxzZSxcInN1YnNjcmlwdGlvbl90eXBlXCI6XCJTVUJTQ1JJUFRJT05cIn0sXCJhbGxvd2VkX2JpbGxpbmdfY3ljbGVzXCI6MCxcInVzZWRfYmlsbGluZ19jeWNsZXNcIjowfV0iLCJzY29wZSI6WyJzdWJzY3JpcHRpb25hcGkiLCJ1c2VyYXBpIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbImRlbGVnYXRpb24iXX0.i1Ub0A8e7CgtOeogghxIfcYoLznCoTTE5fLLZE90ZiXEqR_I9qP0Dlk1q9Zga8Z98Cwpm6G8cgWuh77E6zCNUZeoRDTOieUNt55TwV8XjqduQGzDWEBGGnxWyfwxt0EXByN4CuOSSx-Y13TeTbNirNO5F91uHsXzTxrvGgccknaJxtwyaFIGux0EDnC7Ki1mOslRA57K-bjtWuM-hvIc5o0qrAOd0FOMvn6r5YCqGKDNrlAKqbcXfCQs26fhGDYhAWZRzzV87fhlcKzBsNe7YAdpU1EGQFyCnu5x2S1rAaoTsHqoE_weiqD1qQn9gkPD4BBfNqobID9iiaVQKPUnng "
}',
  CURLOPT_HTTPHEADER => array(
    'Content-Type: application/json'
  ),
));

$response = curl_exec($curl);
curl_close($curl);

$zx = json_decode($response, true);
$image= $zx["assetDetails"]['image_url'];
$img = str_replace('270x152', '1170x658', $image);
$title= $zx["assetDetails"]['title'];
$playit= $zx["keyOsDetails"]['video_token'];

header("Content-Type: application/json");
$errr= array("error" => "Put Here Only ZEE5-TV URL ,  Invalid Input " );
$err =json_encode($errr);


$apii = array("title" => $title, "image" => $img, "url" => $playit, "modified_by" => "Techie Sneh");
$api =json_encode($apii, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);

header("Content-Type: application/json");
echo $api;
  
?>